### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by AcuriosNab** [ChannexIO/instant_booking_page#71]
Hi I'm new to this. I would like to know if there is any tutorial on how to install this book engine. I would like to test it.

**Comment by Judis** [comment]
Hi,

To launch Booking engine you should have `node` version 14 and `yarn`.
Do next steps:

```
git clone git@github.com:ChannexIO/instant_booking_page.git
yarn install
yarn build
```

Then, create `.env` file at root project folder (you can copy it from `.env.example` file or just put next content:
```
REACT_APP_BASE_PATH=
REACT_APP_API_URL=https://staging.channex.io
REACT_APP_PCI_URL=https://pci.channex.io
REACT_APP_CHANNEL_CODE=openshopping
REACT_APP_SEARCH_PAGE_IS_ACTIVE=true
```

Then launch project via `yarn start`.

Please, let me know if you have any other questions.
